version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-south-1 | docker login --username AWS --password-stdin 125903893583.dkr.ecr.eu-south-1.amazonaws.com
      - aws s3 cp s3://projectdaimon-env/.env.minecraft .env
      - docker pull 125903893583.dkr.ecr.eu-south-1.amazonaws.com/daimon-minecraft:latest || true
  build:
    commands:
      - |
        docker build \
          -t "125903893583.dkr.ecr.eu-south-1.amazonaws.com/daimon-minecraft:latest" \
          --cache-from "125903893583.dkr.ecr.eu-south-1.amazonaws.com/daimon-minecraft:latest" \
          .
  post_build:
    commands:
      - docker push 125903893583.dkr.ecr.eu-south-1.amazonaws.com/daimon-minecraft:latest
      - |
        printf \
          '[{"name":"%s","imageUri":"%s"}]' \
          "daimon-minecraft" \
          "125903893583.dkr.ecr.eu-south-1.amazonaws.com/daimon-minecraft:latest" \
          > images.json
artifacts:
  files: images.json